### ISSUE TITLE
离线数据库中的decode_remote表里没有空调的数据

### ISSUE THREAD

**Issue by IAn2018cs** [irext/database#3]
decode_remote 表中 category_id = 1 的数据为空。

**Comment by strawmanbobi** [comment]
确实没有。
decode_remote 实际上是批量运行了解码算法得到的原始格式数据，均为命令码，因为一个固定的遥控器，有几个 button，就只会有几个命令码。
空调是状态码，理论上如果要把一个遥控器的 binary 格式的空调码完全展开成为原始格式数据，那么会有上千个条目（模式5 x 风力4 x 温度16 x 风向4 = 1280），而且因为空调编码的复杂性，不适合这样做。

如果你需要空调码的话，可以仔细看文档，通过调用解码算法的方式，直接从 binary 码库里解出你想要的空调码，非常简单。
